import { NextResponse } from "next/server"

type DatasType = {
    id: number,
    title: string,
    chapter: string,
    description: string,
    module1: string,
    module2: string,
    module3: string,
    color: string,
    image?: any,
    playbutton?: any,
}[]
const ModuleData: DatasType = [
    {
        id: 1,
        title: "Introduction to Stock Markets",
        chapter: "15 chapters",
        description: "The stock market can play a pivotal role in ensuring your financial security. In this module, you will learn how to get started in the stock market, its fundamentals, how it functions, and the various intermediaries that appertain it.",
        module1: "View module",
        module2: "Watch videos",
        module3: " हिंदी",
        color: "#69c969",
    },
    {
        id: 2,
        title: "Technical Analysis",
        chapter: "22 chapters",
        description: "Technical Analysis (TA) helps in developing a point of view. In this module, we will discover the complex attributes, various patterns, indicators, and theories of TA that will help you as a trader to find upright trading opportunities in the market.",
        module1: "View module",
        module2: "Watch videos",
        module3: " हिंदी",
        color: "#1669C9",
    },
    {
        id: 3,
        title: "Fundamental Analysis",
        chapter: "16 chapters",
        description: "The Fundamental Analysis (FA) module explores Equity research by reading financial statements and annual reports, calculating and analyzing Financial Ratios, and evaluating the intrinsic value of a stock to find long-term investing opportunities.",
        module1: "View module",
        module2: "Watch videos",
        module3: " हिंदी",
        color: "#1669C9",
    },
    {
        id: 4,
        title: "Fundamental Analysis",
        chapter: "16 chapters",
        description: "The Fundamental Analysis (FA) module explores Equity research by reading financial statements and annual reports, calculating and analyzing Financial Ratios, and evaluating the intrinsic value of a stock to find long-term investing opportunities.",
        module1: "View module",
        module2: "Watch videos",
        module3: " हिंदी",
        color: "#EACF32",
    },
    {
        id: 5,
        title: "Options Theory for Professional Trading",
        chapter: "25 chapters",
        description: "Options Trading is a segment of the derivatives segment. Options contracts grant the buyer the right to buy/sell the underlying without a compulsory obligation. This module discusses options contracts, pricing, and their profit and loss payoffs.",
        module1: "View module",
        module2: "Watch videos",
        module3: " हिंदी",
        color: "#FFB05A",
    },
    {
        id: 6,
        title: "Option Strategies",
        chapter: "14 chapters",
        description: "A trader can use options strategies to monetize their views on volatility, sentiment, and timing. This module explores various options strategies that can be built with a multi-dimensional approach involving Option Greeks, Risk-Return, etc.",
        module1: "View module",
        module2: "Watch videos",
        module3: " हिंदी",
        color: "#B5B2EA",
    },
    {
        id: 7,
        title: "Markets and Taxation",
        chapter: "8 chapters",
        description: "As a trader in India, you should be informed of the taxes applicable to your investments and trades. This module outlines essential topics like calculating your turnover, preparing balance sheet and P&L statements, and filing your Income Tax Returns.",
        module1: "View module",
        module2: "Watch videos",
        module3: " हिंदी",
        color: "#78DDB9",
    },
    {
        id: 8,
        title: "Currency, Commodity, and Government Securities",
        chapter: "19 chapters",
        description: "Interest rates, forex rates, and inflation impact each other and commodity prices. Commodity prices impact each other, too. This module discusses trading in currency and commodity derivatives and Government Securities (GSec) in the Indian markets.",
        module1: "View module",
        module2: "Watch videos",
        module3: " हिंदी",
        color: "#D1C36F",
    },
    {
        id: 9,
        title: "Risk Management and Trading Psychology",
        chapter: "16 chapters",
        description: "Trading and investing are subject to risks. Our emotions also influence our choices in the market and could aggravate risks. This module discusses risk and risk management tools along with the psychology required for sustaining in the markets.",
        module1: "View module",
        module2: "Watch videos",
        module3: " हिंदी",
        color: "#4EDFEA",
    },
    {
        id: 10,
        title: "Trading Systems",
        chapter: "16 chapters",
        description: "Have you considered building your own Trading System? Well, then, this module is for you. In this module, we will learn about the components of building a good trading system and more, including the techniques and different types of Trading Systems.",
        module1: "View module",
        module2: "Watch videos",
        module3: " हिंदी",
        color: "#FF8773",
    },
    {
        id: 11,
        title: "Personal Finance - Mutual Funds",
        chapter: "32 chapters",
        description: "Managing personal finances can help you achieve your short-term and long-term financial goals. This module encompasses the various aspects of personal finance, such as retirement planning, mutual funds, ETFs, bonds, and goal-oriented investments.",
        module1: "View module",
        module2: "Watch videos",
        module3: " हिंदी",
        color: "#48CBFF",
    },
    {
        id: 12,
        title: "Innerworth - Mind over markets",
        chapter: "603 chapters",
        description: "Originally a collection of newsletters on trading psychology published between 2002 and 2007 by Marketwise, a US stock broking firm, 'Innerworth - Mind over Markets' will guide you and prepare you psychologically to become a rational trader.",
        module1: "View module",
        module2: "Watch videos",
        module3: " हिंदी",
        color: "#ecc3a7",
    },
    {
        id: 13,
        title: "Integrated Financial Modelling",
        chapter: "18 chapters",
        description: "An integrated financial model of a company breaks down the financials of a company to give you granular insights. A financial model includes assets, reserves, debt schedules, cashflows, and valuation models. Learn all that and more in this module.",
        module1: "View module",
        module2: "Watch videos",
        module3: " हिंदी",
        color: "#99b4ff",
    },
    {
        id: 14,
        title: "Personal Finance - Insurance",
        chapter: "9 chapters",
        description: "If you have been working on your financial plan and continuously saving and investing, it is crucial to be prepared to tackle any unforeseen eventualities. The short chapters in this module elucidate the importance of insurance in one's life.",
        module1: "View module",
        module2: "Watch videos",
        module3: " हिंदी",
        color: "#B8D89E",
    },
    {
        id: 15,
        title: "Sector Analysis",
        chapter: "15 chapters",
        description: "Sector analysis is an extension of fundamental analysis. Each sector exhibits unique features and reacts differently to the same market forces. This module helps you understand what to look for in each sector as a stock picker or an equity investor.",
        module1: "View module",
        module2: "Watch videos",
        module3: " हिंदी",
        color: "#E8BB55",
    },
    {
        id: 16,
        title: "Social Stock Exchanges (SSEs)",
        chapter: "4 chapters",
        description: "Social Stock Exchange is a new segment on stock exchanges meant to enable investors to donate/invest in social enterprises. SSEs will act as a bridge between the less-informed but willing donors and legitimate organizations doing real social work.",
        module1: "View module",
        module2: "Watch videos",
        module3: " हिंदी",
        color: "#8cbf71",
    },
]

export async function GET() {
    return NextResponse.json(ModuleData)
}